[workspace]
members = ["core", "periphery", "tests", "client/rs", "lib/*"]

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["mbecker20 <becker.maxh@gmail.com>"]
license = "GPL-3.0-or-later"

[workspace.dependencies]
# local
monitor_macros = { path = "lib/macros" }
monitor_types = { path = "lib/types" }
monitor_client = { path = "client/rs" }
periphery_client = { path = "lib/periphery_client" }
monitor_periphery = { path = "periphery" }
# external
tokio = { version = "1.28", features = ["full"] }
axum = { version = "0.6", features = ["ws", "json", "headers"] }
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.4", features = ["fs", "cors"] }
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "4.3", features = ["derive"] }
uuid = { version = "1.3", features = ["v4", "fast-rng", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-util = "0.7"
futures = "0.3"
futures-util = "0.3"
dotenv = "0.15"
envy = "0.4"
anyhow = "1.0"
log = "0.4"
simple_logger = "4.1"
bollard = "0.14.0"
derive_builder = "0.12"
typeshare = "1.0.1"
strum = "0.25"
strum_macros = "0.25"
sysinfo = "0.29"
async-trait = "0.1"
urlencoding = "2.1"
rand = "0.8"
jwt = "0.16"
hmac = "0.12"
sha2 = "0.10"
bcrypt = "0.15"
hex = "0.4"
aws-config = "0.55"
aws-sdk-ec2 = "0.28"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
# mogh
run_command = { version = "0.0.6", features = ["async_tokio"] }
slack = { package = "slack_client_rs", version = "0.0.8" }
merge_config_files = "0.1.3"
termination_signal = "0.1.2"
async_timing_util = "0.1.14"
partial_derive2 = "0.2.1"
derive_variants = "0.1.1"
make_option = "0.1.3"
resolver_api = "0.1.6"
parse_csl = "0.1.0"
mungos = "0.4.13"
svi = "0.1.4"
