[workspace]
members = ["core", "periphery", "tests", "lib/*"]
exclude = ["lib/ts_client"]

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["mbecker20 <becker.maxh@gmail.com>"]
license = "GPL-3.0-or-later"

[workspace.dependencies]
# local
monitor_helpers = { path = "lib/helpers" }
monitor_types = { path = "lib/types" }
monitor_client = { path = "lib/rs_client" }
periphery_client = { path = "lib/periphery_client" }
monitor_periphery = { path = "periphery" }
# external
tokio = { version = "1.28", features = ["full"] }
axum = { version = "0.6", features = ["ws", "json", "headers"] }
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.4", features = ["fs", "cors"] }
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "4.3", features = ["derive"] }
uuid = { version = "1.3", features = ["v4", "fast-rng", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
envy = "0.4"
anyhow = "1.0"
log = "0.4"
simple_logger = "4.1"
bson = "2.6.1"
bollard = "0.14.0"
diff-struct = "0.5"
derive_builder = "0.12"
typeshare = "1.0.1"
strum = "0.24"
strum_macros = "0.24"
sysinfo = "0.29"
async-trait = "0.1"
partial_derive2 = "0.1.2"
make_option = "0.1.2"
# mogh
run_command = { version = "0.0.6", features = ["async_tokio"] }
slack = { package = "slack_client_rs", version = "0.0.8" }
merge_config_files = "0.1.3"
termination_signal = "0.1.2"
async_timing_util = "0.1.14"
resolver_api = "0.1.3"
parse_csl = "0.1.0"
mungos = "0.3.20"
svi = "0.1.4"

