[workspace]
resolver = "2"
members = ["bin/*", "lib/*", "client/core/rs", "client/periphery/rs"]

[workspace.package]
version = "1.0.1"
edition = "2021"
authors = ["mbecker20 <becker.maxh@gmail.com>"]
license = "GPL-3.0-or-later"

[workspace.dependencies]
# LOCAL
monitor_macros = { path = "lib/macros" }
monitor_client = { path = "client/core/rs" }
periphery_client = { path = "client/periphery/rs" }
logger = { path = "lib/logger" }

# MOGH
run_command = { version = "0.0.6", features = ["async_tokio"] }
serror = { version = "0.1.9", features = ["axum"] }
slack = { version = "0.1.0", package = "slack_client_rs" }
derive_default_builder = "0.1.8"
derive_empty_traits = "0.1.0"
merge_config_files = "0.1.3"
termination_signal = "0.1.3"
async_timing_util = "0.1.14"
partial_derive2 = "0.2.2"
derive_variants = "0.1.3"
mongo_indexed = "0.2.2"
resolver_api = "0.1.8"
parse_csl = "0.1.0"
mungos = "0.5.4"
svi = "0.1.4"

# ASYNC
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.12.0", features = ["json"] }
tokio-util = "0.7.10"
futures = "0.3.30"
futures-util = "0.3.30"
async-trait = "0.1.78"
async-recursion = "1.1.0"

# SERVER
axum = { version = "0.7.4", features = ["ws", "json"] }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.5.2", features = ["fs", "cors"] }
tokio-tungstenite = "0.21.0"

# SER/DE
serde = { version = "1.0.197", features = ["derive"] }
strum = { version = "0.26.2", features = ["derive"] }
serde_json = "1.0.114"
toml = "0.8.12"

# ERROR
anyhow = "1.0.81"
thiserror = "1.0.58"

# LOGGING
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tracing = "0.1.40"

# CONFIG
clap = { version = "4.5.3", features = ["derive"] }
dotenv = "0.15.0"
envy = "0.4.2"

# CRYPTO
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "serde"] }
urlencoding = "2.1.3"
rand = "0.8.5"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
bcrypt = "0.15.1"
hex = "0.4.3"

# SYSTEM
bollard = "0.16.0"
sysinfo = "0.30.7"

# CLOUD
aws-config = "1.1.8"
aws-sdk-ec2 = "1.27.0"

# MISC
derive_builder = "0.20.0"
typeshare = "1.0.2"
