[gen-ts-types]
description = "generates typescript types for the ts client"
path = "."
cmd = "node ./client/ts/generate_types.mjs"

[start-frontend]
path = "frontend"
cmd = "yarn dev"

[monrun-sync]
path = "bin/monrun"
cmd = "cargo run -- sync"