[package]
name = "migrator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monitor_types.workspace = true
logger.workspace = true
#
termination_signal.workspace = true
#
tokio.workspace = true
mungos.workspace = true
anyhow.workspace = true
dotenv.workspace = true
envy.workspace = true
serde.workspace = true
log.workspace = true
chrono = "0.4"