[package]
name = "monitor-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21", features = ["full"] }
axum = { version = "0.5", features = ["ws"] }
axum-extra = { version = "0.3", features = ["spa"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.3", features = ["cors"] }
mungos = "0.2.17"
dotenv = "0.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"