[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helpers = { path = "../lib/helpers" }
db = { package = "db_client", path = "../lib/db_client" }
types = { path = "../lib/types" }
periphery = { package = "periphery_client", path = "../lib/periphery_client" }
tokio = { version = "1.21", features = ["full"] }
axum = { version = "0.5", features = ["ws", "json"] }
axum-extra = { version = "0.3", features = ["spa"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.3", features = ["cors"] }
slack = { package = "slack_client_rs", version = "0.0.7" }
mungos = "0.2.24"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dotenv = "0.15"
envy = "0.4"
oauth2 = "4.2.3"
anyhow = "1.0"
bcrypt = "0.13"
jwt = "0.16"
hmac = "0.12"
sha2 = "0.10"
async_timing_util = "0.1.11"