[package]
name = "monitor-periphery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../lib/types" }
docker = {  package = "docker_client", path = "../lib/docker_client" }
run_command = { version = "0.0.5", features = ["async_tokio"] }
git = { package = "git_client", path = "../lib/git_client" }
tokio = { version = "1.21", features = ["full"] }
axum = { version = "0.5" }
tower = { version = "0.4", features = ["full"] }
dotenv = "0.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bollard = "0.13"
anyhow = "1.0"
envy = "0.4"