[[server]]
name = "monitor-01"
description = ""
tags = ["monitor"]

[server.config]
address = "http://localhost:8120"
enabled = true
stats_monitoring = true
auto_prune = true
send_unreachable_alerts = true
send_cpu_alerts = true
send_mem_alerts = true
send_disk_alerts = true
region = "us-east-2"

## TEMPLATE

[[server_template]]
name = "mogh-template"
description = ""
tags = []

[server_template.config]
type = "Aws"

[server_template.config.params]
region = "us-east-2"
instance_type = "t3.medium"
ami_id = "ami-0005a05fa63a080ab"
subnet_id = "subnet-02ae5ad480eacc4bc"
key_pair_name = "mogh-key"
assign_public_ip = true
use_public_ip = false
port = 8120
user_data = ""
security_group_ids = ["sg-049d98c819f9ace58", "sg-006c0ca638af8eb44"]

[[server_template.config.params.volumes]]
device_name = "/dev/sda1"
size_gb = 20
volume_type = "gp2"
iops = 0
throughput = 0

[[server_template.config.params.volumes]]
device_name = "/dev/sdb"
size_gb = 10
volume_type = "gp3"
iops = 0
throughput = 0

[[server_template]]
name = "hetzno"
description = ""
tags = []

[server_template.config]
type = "Hetzner"

[server_template.config.params]
image = "docker-ce"
automount = true
datacenter = "HillsboroDc1"
private_network_ids = [4258025]
enable_public_ipv4 = true
enable_public_ipv6 = true
firewall_ids = [1402830, 1402832, 1410630]
server_type = "SharedAmd3Core4Ram80Disk"
ssh_keys = ["becker@Beckers-MacBook-Pro.local"]
user_data = """
#cloud-config
runcmd:
  - curl -sSL 'https://raw.githubusercontent.com/mbecker20/monitor/main/scripts/setup-periphery.py' | python3"""
use_public_ip = false
port = 8120

[[server_template.config.params.volumes]]
name = "data"
format = "Xfs"
size_gb = 200
