[package]
name = "monitor_periphery"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "monitor_periphery"
path = "src/lib.rs"

[[bin]]
name = "periphery"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
monitor_types.workspace = true
logger.workspace = true
# mogh
async_timing_util.workspace = true
merge_config_files.workspace = true
parse_csl.workspace = true
termination_signal.workspace = true
run_command.workspace = true
svi.workspace = true
resolver_api.workspace = true
serror.workspace = true
# external
tokio.workspace = true
axum.workspace = true
dotenv.workspace = true
envy.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
bollard.workspace = true
clap.workspace = true
log.workspace = true
simple_logger.workspace = true
uuid.workspace = true
sysinfo.workspace = true
async-trait.workspace = true
