[package]
name = "monitor_periphery"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "periphery"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
monitor_client = { workspace = true, features = ["docker"] }
periphery_client.workspace = true
command.workspace = true
logger.workspace = true
git.workspace = true
# mogh
serror = { workspace = true, features = ["axum"] }
async_timing_util.workspace = true
merge_config_files.workspace = true
parse_csl.workspace = true
run_command.workspace = true
svi.workspace = true
resolver_api.workspace = true
# external
tokio.workspace = true
axum.workspace = true
axum-extra.workspace = true
dotenv.workspace = true
envy.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
bollard.workspace = true
clap.workspace = true
tracing.workspace = true
uuid.workspace = true
sysinfo.workspace = true
