[package]
name = "monitor_cli"
description = "Command line tool to sync monitor resources and execute file defined procedures"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "monitor"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
monitor_client.workspace = true

[dependencies]
# local client
monitor_client = "1.3.0"
# mogh
partial_derive2.workspace = true
# external
tracing-subscriber.workspace = true
serde_json.workspace = true
futures.workspace = true
tracing.workspace = true
colored.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
strum.workspace = true
toml.workspace = true
clap.workspace = true
