## optional. 8120 is default
# port = 8120

## optional. /etc/monitor/repos is default.
# repo_dir = "/home/ubuntu/monitor/repos"

## optional. 5-sec is default. can use 1-sec, 5-sec, 10-sec, 30-sec, 1-min. controls granularity of system stats recorded
# stats_polling_rate = "1-sec"

## optional. default is empty, which will not block any request by ip.
# allowed_ips = ["127.0.0.1"]

## optional. default is empty, which will not require any passkey to be passed by core.
# passkeys = ["abcdefghijk"]

## specify the log level of the monitor core application
## default: info
## options: off, error, warn, info, debug, trace
# logging.level = "debug"

## specify the logging format for stdout / stderr.
## default: standard
## options: standard, json, none
# logging.stdio = "json"

## specify a opentelemetry otlp endpoint to send traces to
## optional, default unassigned
# logging.otlp_endpoint = "http://localhost:4317"

## Set the opentelemetry service name attached to the telemetry this periphery will send.
## Default: "Monitor"
# logging.opentelemetry_service_name = "Monitor-02"

## optional. can inject these values into your deployments configuration.
# [secrets]
# secret_variable = "secret_value"

## optional.
# [github_accounts]
# github_username1 = "github_token1"
# github_username2 = "github_token2"

## optional.
# [docker_accounts]
# docker_username1 = "docker_token1"
# docker_username2 = "docker_token2"
