port = 9001           # optional. 9001 is default
repo_dir = "/repos"   # optional. /repos is default. no reason to change if running the docker container, just mount your desired repo dir to /repos in the container

[secrets] # optional. can inject these values into your deployments configuration.
secret_variable = "secret_value"

[github_accounts] # optional
github_username1 = "github_token1"
github_username2 = "github_token2"

[docker_accounts] # optional
docker_username1 = "docker_token1"
docker_username2 = "docker_token2"