[[build]]
name = "monitor-core-v1"
description = "the prod build for monitor"
tags = ["monitor", "prod", "api"]
config.builder = "mogh-builder"
config.repo = "mbecker20/monitor"
config.branch = "next"
config.build_path = "."
config.dockerfile_path = "bin/core/Dockerfile"
config.docker_account = "mbecker2020"

[[build]]
name = "monitor-frontend-v1"
description = "the prod frontend build for monitor"
tags = ["monitor", "prod", "frontend"]
config.builder = "mogh-builder"
config.repo = "mbecker20/monitor"
config.branch = "next"
config.build_path = "."
config.dockerfile_path = "frontend/Dockerfile"
config.docker_account = "mbecker2020"

[[builder]]
name = "mogh-builder"
description = "the builder for the mogh images"
config.type = "Aws"
config.params.region = "us-east-2"
config.params.instance_type = "c5.2xlarge"
config.params.volume_gb = 20
config.params.ami_id = "ami-01c8bdba63708cde6"
config.params.subnet_id = "subnet-02ae5ad480eacc4bc"
config.params.key_pair_name = "mogh-key"
config.params.assign_public_ip = true
config.params.use_public_ip = false
config.params.port = 8000
config.params.security_group_ids = ["sg-049d98c819f9ace58", "sg-006c0ca638af8eb44"]
config.params.github_accounts = ["mbecker20"]
config.params.docker_accounts = ["mbecker2020"]