[[deployment]]
name = "monitor-core-v1-dev"
description = "v1 dev core api"
tags = ["mogh", "dev"]
config.server_id = "mogh-server"

[[deployment.config.environment]]
variable = "TEST_1"
value = "VALUE"
[[deployment.config.environment]]
variable = "TEST_2"
value = "VALUE"