[[procedure]]
name = "redeploy-v1"
description = "builds v1 core / frontend, and redeploys them"
config.type = "Sequence"

[[procedure.config.data]]
id = ""
enabled = true


# Deploys

[[procedure]]
name = "deploy-v1"
description = "deploys v1 core / frontend"
config.type = "Parallel"
[[procedure.config.data]]
id = "deploy-v1-core"
enabled = true
[[procedure.config.data]]
id = "deploy-v1-frontend"
enabled = true

[[procedure]]
name = "deploy-v1-core"
config.type = "Execution"
config.data.type = "Deploy"
config.data.params.deployment = "monitor-core-v1"

[[procedure]]
name = "deploy-v1-frontend"
config.type = "Execution"
config.data.type = "Deploy"
config.data.params.deployment = "monitor-frontend-v1"

# Builds

[[procedure]]
name = "build-v1"
description = "builds v1 core / frontend"
config.type = "Parallel"
[[procedure.config.data]]
id = "build-v1-core"
enabled = true
[[procedure.config.data]]
id = "build-v1-frontend"
enabled = true

[[procedure]]
name = "build-v1-core"
config.type = "Execution"
config.data.type = "RunBuild"
config.data.params.build = "monitor-core-v1"

[[procedure]]
name = "build-v1-frontend"
config.type = "Execution"
config.data.type = "RunBuild"
config.data.params.build = "monitor-frontend-v1"
