[[user_group]]
name = "uso_groupo"
users = ["becker.maxh", "defi moses"]

[[user_group.permission]]
target.type = "Server"
target.id = "mogh-server"
level = "Read"

[[user_group.permission]]
target.type = "Deployment"
target.id = "monitor-core-v1-dev"
level = "Execute"

[[user_group.permission]]
target.type = "Deployment"
target.id = "monitor-frontend-v1-dev"
level = "Execute"

[[user_group.permission]]
target.type = "Build"
target.id = "monitor-core-next"
level = "Execute"

[[user_group.permission]]
target.type = "Build"
target.id = "monitor-frontend-next"
level = "Execute"